### ISSUE TITLE
Clicking "Create account" or "Sign in" closes dropdown box instead of switching content

### ISSUE THREAD

**Issue by joryphillips** [SharpenedSpoon/accounts-ui-semantic-ui#1]
Basically as the title says - is there a way to make it not close the dropdown when "create account" or "sign in" at the bottom of the dropdown box are clicked? Thanks!

**Comment by iandfox** [comment]
I would love to know this too! This has been bugging me since release. It's because the links to change the flow you are in are "items." As I read it, it seems as tough semantic wants you just to use dropdowns as, basically, replacements for <select> tags, or straight submenus from navigation. There's not a ton of wiggle room within them to include, say, a form! If you look at the markup I used for the form, it is... hacky. But it's what I needed to do to get it to work.

Anyway, I want to solve this too. I was thinking maybe just have everything be buttons? It won't look as nice, but at least it won't close the dropdown.

**Comment by joryphillips** [comment]
Semantic does indeed seem pretty rigid about its dropdown pattern! I thought about separate buttons as well, but I'd prefer helping to get the dropdown working.

I'm new to both, but this is a good opportunity to get to know Meteor and Semantic UI better -- I'll try going through the code to see if I can come up with different options or solutions. Thanks for the great work!

**Comment by joryphillips** [comment]
I think I solved it. Looking at login-buttons-dropdown.js, Template._loginButtonsLoggedOutDropdown.events needs to have an event.stopPropagation added to two places: 
`'click #signup-link': function (event) {
        event.stopPropagation();`

and 

`'click #back-to-login-link': function (event) {
        event.stopPropagation();`

Then, the "Create Account" tag in login-buttons-dropdown.html (line 95) needs to have its id changed from 'back-to-login-link' to 'signup-link', which I believe is more accurate and its intended use. Let me know if you want me to fork, etc.

**Comment by iandfox** [comment]
I could swear I've tried that before, but maybe not so directly! Thanks a lot - if you want to fork you are more than welcome to, otherwise I will make the changes... eventually. When work calms down :)

**Comment by joryphillips** [comment]
My pleasure. I think I'll stay away from forking. In the future, it might be worthwhile to use the latest bootstrap version as a base -- it is how I found the solution. If you ever decide you want to do that, I'll pitch in. Cheers!

**Comment by iandfox** [comment]
By bootstrap, you mean semantic? Or do you mean the bootstrap accounts-ui version?

**Comment by joryphillips** [comment]
The latter, sorry. meteor-accounts-ui-bootstrap-3-master. It could be a terrible idea, but it seems like it has been worked on and thought through a lot more than accounts-ui-unstyled.

**Comment by joryphillips** [comment]
I found one other thing that needed to be fixed, so I'll fork and make a pull request of it all for you to check out.

**Comment by iandfox** [comment]
Solved by pull request #2 - thanks joryphillips!

**Comment by iandfox** [comment]
Thanks a lot for the help, and for the pull request!

I added a new Accounts.ui.config option (dropdownTransition - great idea!) and pushed the new version up to atmosphere. Woohoo! This bug has been annoying me for a while :)
