### ISSUE TITLE
"Password changed" success message needs dismiss

### ISSUE THREAD

**Issue by joryphillips** [SharpenedSpoon/accounts-ui-semantic-ui#3]
I hope I don't get in trouble for this, but I found something else! Upon a successful password change, I can't seem to get the "Password changed" message to go away. I can hide the dialogue by clicking my username, but I can't get back to the Change password/Sign out dialogue. 

It looks like it is assigned as something called "infoMessage" and I'm not immediately sure what could fix it. I can take a closer look at it next week, if it helps. :)

**Comment by iandfox** [comment]
You definitely won't get in trouble! Can you test all my projects? :)

I will look at this, as well - race ya!

**Comment by funkytaco** [comment]
:+1:

**Comment by iandfox** [comment]
@joryphillips Can't thank you enough for all the work you've put into this! I'm all married now, and back at work. I pushed v1.2.0 with all of your changes. If you're ever in Arizona let me know and I'll buy you a beer :)

**Comment by joryphillips** [comment]
@SharpenedSpoon My pleasure -- thank you for creating this package in the first place! Welcome back & congrats again. I'll certainly take you up on the beer if I am in Arizona.
