### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by rbabayoff** [SharpenedSpoon/accounts-ui-semantic-ui#8]
Hey,

First, thanks  for this package. I installed it, and put loginButtons inside a simple semantic ui menu and encountered a few UI issues. You can see the attached screenshot, The issues are:
1. I think caret should be to the right of the Sign In text, not to the left, which is standard for web drop down menus.
2. There needs to be a bit of a margin / padding between caret and text.

The code I use is (I just include it from the html body in a simple `meteor create` project):

```
<template name="navbar">
  <div class="ui menu">
    <a class="active item">
      Home
    </a>
    <a class="item">
      Messages
    </a>
    <a class="item">
      Friends
    </a>
    <div class="right menu">
      <div class="item">
        <div class="ui icon input">
          <input type="text" placeholder="Search...">
          <i class="search link icon"></i>
        </div>
      </div>
      <a class="ui item">
        {{> loginButtons}}
      </a>
    </div>
  </div>
</template>
```

It's code I took from one of semantic ui's menu examples. I also tried to modify it a bit, but caret keeps "touching" text and stays to the left.
![loginbuttons](https://cloud.githubusercontent.com/assets/3960877/9290238/0da5ce1e-4359-11e5-832e-88231034b3ce.png)

**Comment by abernix** [comment]
The current _published_ version of the plugin has the problem you described, but if you use the Git version, it will work fine.  @SharpenedSpoon, any chance of publishing the new version with the recent fixes?

**Comment by abernix** [comment]
See #7

**Comment by rbabayoff** [comment]
@abernix , good to know. Tks!

**Comment by abernix** [comment]
@SharpenedSpoon ping?

**Comment by ghost** [comment]
@SharpenedSpoon ping?

**Comment by iandfox** [comment]
Pong! Sorry folks! On it.

**Comment by iandfox** [comment]
All pushed! Sorry about that - moved into a new city. Thanks @abernix and @brianmingus for the ping!

**Comment by abernix** [comment]
No worries – and thanks!  Welcome to your new stomping ground! :wink:
